### ISSUE TITLE
pasted from dnz lol

### ISSUE THREAD

**Issue by cashtwizzy** [PlantBronze/Anti-Backdoor#1]
pasted from dnz lol https://github.com/spreadmeow/dnz_protector/blob/0c3a76bc1519d9834634228f223f00c823e8b822/server.lua#L1325

**Comment by PlantBronze** [comment]
No one cares about Dnz, this GitHub post is only anti backdoor Bruh if u look at my dc u see it idiot

**Comment by cashtwizzy** [comment]
stay mad paster
